#!/usr/bin/env bash

# Remote Command (rc): A command-line System Administration tool written in bash 4.2+.
# https://github.com/zpiatt/rc
#
# Copyright (C) 2026 Zac Piatt
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

readonly VERSION="Remote Command (rc) version: 0.5.1-beta - August 20, 2026"


execute_selection() {
    case "$selected" in
        "$run_command") [[ "${#selected_hosts[@]}" -gt 0 ]] && run_command ;;
        "$select_all")
            local host

            for host in "${hosts[@]:0:${run_command}}"; do
                selected_hosts["$host"]=1
            done

            selected="$run_command"
        ;;

        "$clear_selection")
            selected_hosts=()
            selected=0
        ;;

        "$quit") exit 0 ;;
        *)
            tput clear
            tput cnorm
            ssh -qo ConnectTimeout=3 "${user}@${hosts[$selected]}"
            tput civis
        ;;
    esac
}


fetch_hosts() {
    readarray -t hosts < <(awk '!/^\s*$|^#/ && !x[tolower($1)]++ {print tolower($1)}' "$file")

    [[ -n "$icmp" || -n "$tcp" || -n "$port" ]] && filter_hosts

    [[ -z "${hosts[*]}" ]] && { printf "No matching hosts.\n" >&2; exit 1; }

    hosts+=("[R]un command" "[S]elect all" "[C]lear selection" "[Q]uit")

    lines="$(tput lines)"
    last_host=$(( ${#hosts[@]} - 5 ))
    run_command=$(( ${#hosts[@]} - 4 ))
    select_all=$(( ${#hosts[@]} - 3 ))
    clear_selection=$(( ${#hosts[@]} - 2 ))
    quit=$(( ${#hosts[@]} - 1 ))

    (( ${#hosts[@]} > lines )) && \
        { printf "Too many hosts to display in current console size\n"  >&2; exit 1; }
}


filter_hosts() {
    declare -a filtered_hosts

    filtered_hosts=("${hosts[@]}")

    if [[ -n "$icmp" ]]; then
        readarray -t filtered_hosts < <( \
            printf "%s\n" "${filtered_hosts[@]}" | \
            xargs -P 50 -I {} bash -c "ping -W1 -c1 {} &> /dev/null && echo {}"
        )
    fi

    if [[ -n "$tcp" || -n "$port" ]]; then
        readarray -t filtered_hosts < <( \
            printf "%s\n" "${filtered_hosts[@]}" | xargs -P 50 -I {} \
            bash -c "timeout 1 bash -c ':> /dev/tcp/{}/${port:-22}' &> /dev/null && echo {}"
        )
    fi

    hosts=("${filtered_hosts[@]}")
}


get_args() {
    local option

    while getopts ':f:hip:tu:v' option; do
        case "$option" in
            f) file="$OPTARG" ;;
            h) usage; exit 0 ;;
            i) icmp="true" ;;
            p) port="$OPTARG" ;;
            t) tcp="true" ;;
            u) user="$OPTARG" ;;
            v) printf "%s\n" "$VERSION"; exit 0 ;;
            ?)
                printf "rc: invalid option -- '%s'\n" "$OPTARG" >&2
                printf "Try 'rc -h' for more information.\n" >&2; exit 1
            ;;
        esac
    done

    shift "$(( OPTIND -1 ))"

    [[ -f "$file" ]] || { printf "file not found: '%s'\n" "$file" >&2; exit 1; }
}


get_selection() {
    local key

    IFS= read -rsn1 key
    case "${key,,}" in
        r) selected="$run_command" ;;
        s) selected="$select_all" ;;
        c) selected="$clear_selection" ;;
        q) selected="$quit" ;;
        h) (( selected > last_host )) && move_cursor -1 ;;
        k) move_cursor -1 ;;
        j) move_cursor 1 ;;
        l) (( selected > last_host )) && move_cursor 1 ;;
        $'\t') selected="$run_command" ;;
        $'\e')
            read -rsn2 -t 0.1 key
            case "$key" in
                "[A") move_cursor -1 ;;
                "[B") move_cursor 1 ;;
                "[C") (( selected > last_host )) && move_cursor 1 ;;
                "[D") (( selected > last_host )) && move_cursor -1 ;;
            esac
        ;;

        $'\x20') (( selected <= last_host )) && toggle_selection ;;
        "") execute_selection ;;
        *) ;;
    esac
}


move_cursor() {
    local direction="$1"

    (( selected += direction ))
    (( selected > quit )) && selected=0
    (( selected < 0 )) && selected="$quit"
}


print_menu() {
    local index host checkbox

    for index in "${!hosts[@]}"; do
        host="${hosts[$index]}"

        if (( index <= last_host )); then
            [[ -n "${selected_hosts["$host"]}" ]] && checkbox="[X]" || checkbox="[ ]"
        fi

        (( index == selected )) && host="\e[7m${host}\e[27m"

        if (( index <= last_host )); then
            printf "%s  %b\n" "$checkbox" "$host"
        else
            printf "%b    " "$host"
        fi

        (( index == last_host )) && printf "\n"
    done

    tput cup $(( quit -1 )) 0
}


run_command() {
    local history_file remote_command confirm host

    history_file="${HOME}/.bash_history"
    history -r "$history_file"

    tput cnorm
    read -erp $'\nEnter remote command: ' remote_command
    printf "Run: '%s'\n" "$remote_command"
    read -erp "on selected hosts? [y/N]: " confirm
    tput civis

    [[ "${confirm,,}" =~ ^y(es)?$ ]] || return 0

    history -s "$remote_command"
    history -w "$history_file"

    for host in "${!selected_hosts[@]}"; do
        printf "\n%s@%s [%s]:$ %s\n" "$user" "$host" "$(date)" "$remote_command"
        ssh -qto ConnectTimeout=3 "${user}@${host}" "$remote_command" 
    done

    read -rsp $'\nPress any key to continue' -n1
}


toggle_selection() {
    local host

    host="${hosts[$selected]}"

    if [[ -n "${selected_hosts[$host]}" ]]; then
        unset "selected_hosts[$host]"
    else
        selected_hosts["$host"]=1
    fi
}


usage() {
    printf "Usage: rc [OPTION]...\n"
    printf "Initialize connection or execute remote commands on target systems.\n\n"
    printf " -f, specify host list as file (rc -f hosts.txt)\n"
    printf " -h, display help and exit\n"
    printf " -i, filter hosts with ICMP echo-request\n"
    printf " -p, filter hosts with TCP handshake on specified port (rc -p 443)\n"
    printf " -t, filter hosts with TCP handshake on port 22\n"
    printf " -u, specify remote user name\n"
    printf " -v, display version number and exit\n\n"
    printf "Full documentation <https://github.com/zpiatt/remote-command>\n"
}


main() {
    file="${HOME}/.config/rc/hosts"
    user="$USER"
    selected=0
    declare -A selected_hosts

    get_args "$@"
    fetch_hosts

    set -o emacs
    trap 'tput cnorm; tput clear' EXIT
    trap '' INT

    while true; do
        tput clear
        tput civis
        print_menu
        get_selection
    done
}

main "$@"
