.TH REMOTE-COMMAND "1" "August 2026" "rc version: 1.0.0" "User Commands"
.SH NAME
Remote Command \- remote management system administration tool.
.SH SYNOPSIS
.B rc
[\fI\,OPTION\/\fR]...
.SH DESCRIPTION
Placeholder
.BR
.TP
Placeholder
.SH OPTIONS
.TP
\fB\-h\fR,
display help and exit
.BR
.TP
\fB\-v\fR,
display version number and exit
.SH "MOVEMENT KEYS"
.TP
\fBSPACEBAR\fR, toggle host selection
.BR
.TP
\fBENTER\fR, execute selection
.BR
.TP
\fBUP/DOWN ARROWS\fR, Move cursor
.BR
.TP
\fBr\fR, move cursor to '[R]un command'
.BR
.TP
\fBc\fR, move cursor to '[C]lear selection'
.BR
.TP
\fBq\fR, move cursor to '[Q]uit'
.SH AUTHOR
Written by Zac Piatt.
.SH "REPORTING BUGS"
Report any bugs to <zpiatt@protonmail.com>
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH "SEE ALSO"
Full documentation <https://github.com/zpiatt/remote-command>
